name: tshl_tawsil
description: Tshl Tawsil - Taxi Booking App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Flutter Version: 3.32.0
# Dart Version: 3.8.0
version: 1.0.4

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get: ^4.6.6
  fl_country_code_picker: ^0.1.9+1
  pinput: ^5.0.0
  geolocator: ^13.0.1
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  bottom_bar_with_sheet: ^2.4.0
  dotted_line: ^3.2.3
  flutter_polyline_points:
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.3.2
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.1.0
  nb_utils: ^7.0.3
  flutter_feather_icons: ^2.0.0+1
  flutter_iconly: ^1.0.2
  provider: ^6.1.0
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3
  country_code_picker: ^3.0.0
  font_awesome_flutter: ^10.7.0
  community_material_icon: ^5.9.55
  material_design_icons_flutter: ^7.0.7296
  flutter_credit_card: ^4.0.1
  flag: ^7.0.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/icons/
  fonts:
    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato-Medium
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato-Semibold
      fonts:
        - asset: assets/fonts/Lato-Semibold.ttf

